export const SET_AUTHED_USER = "SET_AUTHED_USER";

export const ADD_QUESTION = "ADD_QUESTION";
export const ADD_ANSWERED_BY_USER = "ADD_ANSWERED_BY_USER";
export const ADD_USERS_CHOICE = "ADD_USERS_CHOICE";
export const RECEIVE_QUESTIONS = "RECEIVE_QUESTIONS";

export const ADD_USER = "ADD_USER";
export const ADD_ASKED_QUESTION = "ADD_ASKED_QUESTION";
export const ADD_ANSWERED_QUESTION = "ADD_ANSWERED_QUESTION";
export const RECEIVE_USERS = "RECEIVE_USERS";
